-- Load core modules
require("settings")
require("plugins")
require("autopairs")
require("colors")
require("comment")
require("dap-plug")
require("git")
require("keymaps")
require("lsp")
require("statusline")
require("telescope-plug")
require("tree")
require("treesitter")
require("conform-plug")
require("linting")
